/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BookRouteImport } from './routes/book'
import { Route as CareRouteImport } from './routes/care'
import { Route as ConnecticutWebDesignRouteImport } from './routes/connecticut-web-design'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HartfordWebDesignRouteImport } from './routes/hartford-web-design'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as WhyRouteImport } from './routes/why'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiPortalRouteImport } from './routes/api/portal'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnecticutWebDesignRoute = ConnecticutWebDesignRouteImport.update({
  id: '/connecticut-web-design',
  path: '/connecticut-web-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HartfordWebDesignRoute = HartfordWebDesignRouteImport.update({
  id: '/hartford-web-design',
  path: '/hartford-web-design',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalRoute = ApiPortalRouteImport.update({
  id: '/api/portal',
  path: '/api/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/book': typeof BookRoute
  '/care': typeof CareRoute
  '/connecticut-web-design': typeof ConnecticutWebDesignRoute
  '/contact': typeof ContactRoute
  '/hartford-web-design': typeof HartfordWebDesignRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/thanks': typeof ThanksRoute
  '/why': typeof WhyRoute
  '/api/contact': typeof ApiContactRoute
  '/api/portal': typeof ApiPortalRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/book': typeof BookRoute
  '/care': typeof CareRoute
  '/connecticut-web-design': typeof ConnecticutWebDesignRoute
  '/contact': typeof ContactRoute
  '/hartford-web-design': typeof HartfordWebDesignRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/thanks': typeof ThanksRoute
  '/why': typeof WhyRoute
  '/api/contact': typeof ApiContactRoute
  '/api/portal': typeof ApiPortalRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/book': typeof BookRoute
  '/care': typeof CareRoute
  '/connecticut-web-design': typeof ConnecticutWebDesignRoute
  '/contact': typeof ContactRoute
  '/hartford-web-design': typeof HartfordWebDesignRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/thanks': typeof ThanksRoute
  '/why': typeof WhyRoute
  '/api/contact': typeof ApiContactRoute
  '/api/portal': typeof ApiPortalRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/book'
    | '/care'
    | '/connecticut-web-design'
    | '/contact'
    | '/hartford-web-design'
    | '/pay'
    | '/privacy'
    | '/services'
    | '/thanks'
    | '/why'
    | '/api/contact'
    | '/api/portal'
    | '/api/stripe-webhook'
    | '/work/$slug'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/book'
    | '/care'
    | '/connecticut-web-design'
    | '/contact'
    | '/hartford-web-design'
    | '/pay'
    | '/privacy'
    | '/services'
    | '/thanks'
    | '/why'
    | '/api/contact'
    | '/api/portal'
    | '/api/stripe-webhook'
    | '/work/$slug'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/book'
    | '/care'
    | '/connecticut-web-design'
    | '/contact'
    | '/hartford-web-design'
    | '/pay'
    | '/privacy'
    | '/services'
    | '/thanks'
    | '/why'
    | '/api/contact'
    | '/api/portal'
    | '/api/stripe-webhook'
    | '/work/$slug'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BookRoute: typeof BookRoute
  CareRoute: typeof CareRoute
  ConnecticutWebDesignRoute: typeof ConnecticutWebDesignRoute
  ContactRoute: typeof ContactRoute
  HartfordWebDesignRoute: typeof HartfordWebDesignRoute
  PayRoute: typeof PayRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  ThanksRoute: typeof ThanksRoute
  WhyRoute: typeof WhyRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiPortalRoute: typeof ApiPortalRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connecticut-web-design': {
      id: '/connecticut-web-design'
      path: '/connecticut-web-design'
      fullPath: '/connecticut-web-design'
      preLoaderRoute: typeof ConnecticutWebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hartford-web-design': {
      id: '/hartford-web-design'
      path: '/hartford-web-design'
      fullPath: '/hartford-web-design'
      preLoaderRoute: typeof HartfordWebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal': {
      id: '/api/portal'
      path: '/api/portal'
      fullPath: '/api/portal'
      preLoaderRoute: typeof ApiPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BookRoute: BookRoute,
  CareRoute: CareRoute,
  ConnecticutWebDesignRoute: ConnecticutWebDesignRoute,
  ContactRoute: ContactRoute,
  HartfordWebDesignRoute: HartfordWebDesignRoute,
  PayRoute: PayRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  ThanksRoute: ThanksRoute,
  WhyRoute: WhyRoute,
  ApiContactRoute: ApiContactRoute,
  ApiPortalRoute: ApiPortalRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
